version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: demo_ferme
      MYSQL_USER: ismail
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      timeout: 20s
      retries: 10
    networks:
      - backend
  backend:
    build: ./back
    container_name: spring-backend
    ports:
      - "8083:8082"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: ismail
      MYSQL_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend
  frontend:
    build: ./front
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - frontend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
  frontend:
